import React,{useState}from"react";import{createRoot}from"react-dom/client";import{motion}from"framer-motion";import{CalendarDays,Clock,MapPin,Phone,Star,Instagram,Flame,Heart,Leaf,Users,ShoppingBag,ExternalLink,ChevronRight,Mail}from"lucide-react";import"./styles.css";
const takeaway="https://www.takeaway.com/be-fr/menu/pizzeria-vaillance",phone="tel:+32230739774",maps="https://www.google.com/maps/search/?api=1&query=Place%20de%20la%20Vaillance%2010%201070%20Anderlecht";
const menu={pizzas:[["Margherita","Tomate, mozzarella, basilic","9,50€"],["Funghi","Tomate, mozzarella, champignons","10€"],["Parmigiana","Tomate, mozzarella, aubergines","10,50€"],["Prosciutto","Tomate, mozzarella, jambon","11€"],["Regina","Tomate, mozzarella, jambon, champignons","11,50€"],["Caprese","Tomate, mozzarella, tomates cerises, basilic","12€"],["Capricciosa","Jambon, champignons, artichauts","12,50€"],["Quattro Stagioni","Jambon, champignons, artichauts, olives","13,50€"],["Vegetariana","Aubergines, poivrons, courgettes, olives","14€"],["Parma","Jambon de Parme, roquette, parmesan","15,50€"]],pates:[["Pasta Arrabbiata","Sauce tomate relevée","10€"],["Pasta Bolognaise","Sauce bolognaise maison","11,50€"],["Pasta Carbonara","Crème, lardons, parmesan","11,50€"],["Pasta Pollo & Funghi","Poulet et champignons","14,50€"],["Frutti di mare","Pâtes aux fruits de mer","15€"]],boissons:[["Espresso","Café italien","2,50€"],["Cappuccino","Café au lait mousseux","3,50€"],["Coca-Cola / Zero","33cl","2,50€"],["Ice Tea","33cl","2,50€"],["Red Bull","25cl","3,50€"]],vins:[["Jupiler","Bière","2,50€"],["Leffe Blonde / Brune","Bière belge","3,50€"],["Corona","Bière bouteille","4,50€"],["Verre de vin","Blanc, rouge ou rosé","3,50€"],["Vin 1/2L","Blanc, rouge ou rosé","10€"]]};
function Reveal({ children, className = "", delay = 0 }) {
  return (
    <motion.div
      className={className}
      initial={{ opacity: 0, y: 42 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.18 }}
      transition={{ duration: 0.72, ease: [0.22, 1, 0.36, 1], delay }}
    >
      {children}
    </motion.div>
  );
}

function Header(){return <header className="header"><a href="#home" className="logo"><span>Pizzeria</span>Vaillance<small>Anderlecht</small></a><nav><a href="#home">Accueil</a><a href="#menu">Menu</a><a href="#ambiance">À propos</a><a href="#gallery">Galerie</a><a href="#avis">Avis</a><a href="#contact">Contact</a></nav><a href={phone} className="reserve"><CalendarDays size={18}/>Réserver une table</a></header>}
function Hero(){return <section id="home" className="hero"><motion.div className="heroBg" initial={{ scale: 1.06 }} animate={{ scale: 1 }} transition={{ duration: 1.6, ease: "easeOut" }} /><motion.div className="heroContent" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.8}}><p className="script">Le vrai goût de l’Italie <span>🇮🇹</span></p><h1>Au cœur d’Anderlecht</h1><p className="lead">Des pizzas artisanales, des pâtes fraîches et une cuisine généreuse, dans une ambiance chaleureuse qui invite à savourer l’instant.</p><p className="stars"><Star fill="currentColor" size={19}/>4,7/5 sur Google — +150 avis</p><div className="actions"><a className="btn gold" href={takeaway} target="_blank"><ShoppingBag size={18}/>Commander maintenant</a><a className="btn dark" href="#menu">Voir le menu</a><a className="btn dark" href={phone}><Phone size={18}/>Appeler</a></div></motion.div><div className="quick"><div><Clock/><b>Ouvert 7j/7</b><span>09h00 – 23h00</span></div><a href={maps} target="_blank"><MapPin/><b>Place de la Vaillance 10</b><span>1070 Anderlecht</span></a><a href={phone}><Phone/><b>02 30 73 97 74</b><span>Réservation & commande</span></a></div></section>}
const cards=[["Quattro Stagioni","13,50€","Pizza, champignons, jambon, olives, artichauts"],["Caprese Bruschettas","11€","Tomates fraîches, mozzarella, olives, basilic"],["Salade Poulet","13€","Poulet grillé, tomates, olives, roquette, parmesan"],["Pâtes Bolognaise","12€","Pâtes fraîches, sauce bolognaise maison, parmesan"]];
function Specialites(){return <section className="specialites"><Reveal className="intro"><span>Découvrez</span><h2>Nos Spécialités</h2><p>Une sélection de recettes préparées avec des ingrédients frais, inspirées de la tradition italienne et revisitées avec soin.</p><a className="outline" href="#menu">Voir tout le menu <ChevronRight size={16}/></a></Reveal><Reveal className="cards" delay={0.12}>{cards.map((c,i)=><motion.article className="card" key={c[0]} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}}><img src="/src/assets/home-base.jpg"/><div><h3>{c[0]}</h3><b>{c[1]}</b><p>{c[2]}</p></div></motion.article>)}</Reveal></section>}
function Menu(){const[tab,setTab]=useState("pizzas");const labels={pizzas:"Pizzas",pates:"Pâtes fraîches",boissons:"Boissons",vins:"Bières & vins"};return <section id="menu" className="menu"><Reveal className="menuTop"><div><p className="script">Notre menu 🇮🇹</p><h2>La carte Vaillance</h2><p>Des recettes authentiques préparées avec des ingrédients frais et sélectionnés avec soin.</p></div><a href={takeaway} target="_blank" className="btn gold">Commander sur Takeaway <ExternalLink size={17}/></a></Reveal><Reveal className="tabs" delay={0.08}>{Object.keys(menu).map(k=><button onClick={()=>setTab(k)} className={tab===k?"active":""} key={k}>{labels[k]}</button>)}</Reveal><motion.div key={tab} className="menuGrid" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}}>{menu[tab].map(([n,d,p])=><article className="mi" key={n}><div><h3>{n}</h3><p>{d}</p></div><strong>{p}</strong></article>)}</motion.div></section>}
function Ambiance(){return <section id="ambiance" className="ambiance"><Reveal className="ambImg"></Reveal><Reveal className="ambText" delay={0.12}><span>Notre ambiance</span><h2>Un lieu où il fait bon de se retrouver</h2><p>Plongez dans l’atmosphère chaleureuse de notre pizzeria, un lieu où l’on se retrouve pour partager un moment convivial autour d’une cuisine italienne authentique.</p><div className="values"><div><Leaf/>Ingrédients frais & locaux</div><div><Flame/>Cuisson au feu de bois</div><div><Users/>Ambiance conviviale</div><div><Heart/>Fait avec passion</div></div></Reveal></section>}
function Gallery(){return <section id="gallery" className="gallery"><Reveal><h2>Moments de partage</h2><p className="script">Suivez-nous</p><a className="insta" href="https://instagram.com/pizzeriavaillance" target="_blank"><Instagram/>@pizzeriavaillance</a><a className="outline" href="https://instagram.com/pizzeriavaillance" target="_blank">Voir plus sur Instagram <ChevronRight size={16}/></a></Reveal><Reveal className="galGrid" delay={0.12}>{[1,2,3,4].map(i=><img key={i} src="/src/assets/home-base.jpg"/>)}</Reveal></section>}
function Footer(){return <footer id="contact" className="footer"><div><a className="logo" href="#home"><span>Pizzeria</span>Vaillance<small>Anderlecht</small></a><p>Le vrai goût de l’Italie au cœur d’Anderlecht. Une cuisine généreuse, des produits sélectionnés avec soin et une ambiance conviviale.</p></div><div><h3>Liens rapides</h3><a>Accueil</a><a>Menu</a><a>À propos</a><a>Galerie</a><a>Avis</a><a>Contact</a></div><div><h3>Horaires</h3><p>Lundi – Dimanche<br/>09h00 – 23h00</p><span>Ouvert 7j/7</span></div><div><h3>Contact</h3><p><MapPin size={16}/>Place de la Vaillance 10, 1070 Anderlecht</p><p><Phone size={16}/>02 30 73 97 74</p><p><Mail size={16}/>info@pizzeriavaillance.be</p><p><Instagram size={16}/>@pizzeriavaillance</p></div><small>© 2026 Pizzeria Vaillance. Tous droits réservés.</small></footer>}
function App(){return <><Header/><Hero/><Specialites/><Menu/><Ambiance/><Gallery/><section id="avis" className="cta"><Reveal><p className="script">Envie d’une bonne pizza ?</p><h2>Réservez ou commandez dès maintenant</h2><a href={phone} className="btn gold">Appeler maintenant</a><a href={takeaway} target="_blank" className="btn dark">Commander sur Takeaway</a></Reveal></section><Footer/><a className="mobile" href={phone}><Phone size={18}/>Appeler</a></>}
createRoot(document.getElementById("root")).render(<App/>);
