const menuData=[
{cat:'pizzas',title:'Qui de mieux qu’une bonne pizza ?',items:[['Pizza Margherita','€9.50','sauce tomate, mozzarella, basilic, origan'],['Pizza Funghi','€10.00','sauce tomate, mozzarella, champignons'],['Pizza Parmigiana','€10.50','sauce tomate, mozzarella, aubergines'],['Pizza Prosciutto','€11.00','sauce tomate, mozzarella, jambon'],['Pizza Pepperoni','€11.00','sauce tomate, mozzarella, salami, poivrons'],['Pizza Regina','€11.50','sauce tomate, mozzarella, jambon, champignons'],['Pizza Caprese','€12.00','sauce tomate, mozzarella, tomates cerise, tranche de mozzarella, basilic, origan'],['Pizza Calzone','€12.00','sauce tomate, mozzarella, jambon, champignons, œuf'],['Pizza Siciliana','€12.50','sauce tomate, mozzarella, salami, câpres, olives'],['Pizza Capricciosa','€12.50','sauce tomate, mozzarella, jambon, câpres, champignons, artichauts'],['Pizza Napoli','€12.50','sauce tomate, mozzarella, câpres, anchois, origan'],['Pizza Hawaïan','€13.00','sauce tomate, mozzarella, jambon, ananas'],['Pizza Tonno','€13.50','sauce tomate, mozzarella, thon, olives'],['Pizza 4 Formaggi','€13.50','sauce tomate, mozzarella, gorgonzola, parmesan, taleggio'],['Pizza 4 Stagioni','€13.50','sauce tomate, mozzarella, jambon, champignons, artichauts, poivrons, olives'],['Pizza Vegetariana','€14.00','sauce tomate, mozzarella, aubergines, poivrons, courgettes, champignons, olives'],['Pizza Scampi','€14.00','sauce tomate, mozzarella, scampis'],['Pizza Pola','€14.00','sauce tomate, mozzarella, poulet'],['Pizza Rucola','€14.00','sauce tomate, mozzarella, roquette'],['Pizza Frutti di Mare','€15.00','sauce tomate, mozzarella, fruits de mer'],['Pizza Parma','€15.50','sauce tomate, mozzarella, jambon de parme, parmesan'],['Pizza Carpaccio','€15.50','sauce tomate, mozzarella, bresaola, roquette']]},
{cat:'pates',title:'Pour les amoureux de pâtes',items:[['Pasta Arrabbiata','€10.00',''],['Pasta Bolognese','€11.50',''],['Pasta Carbonara','€11.50',''],['Pasta Vegetariana','€13.50',''],['Pasta Pola & Funghi','€14.50',''],['Pasta Scampis & courgettes','€14.50',''],['Pasta Frutti di mare','€15.00','']]},
{cat:'boissons',title:'De quoi se rafraîchir',items:[['Eau plate 25cl','€2.50',''],['Fanta','€2.50',''],['Coca-Cola','€2.50',''],['Coca-Cola Zero','€2.50',''],['Sprite','€2.50',''],['Red Bull','€3.50',''],['Looza pêche / orange / fraise / cerises','€2.50',''],['Ice Tea Lemon','€2.50',''],['Ice Tea Pêche','€2.50',''],['Ice Tea Green','€2.50',''],['Schweppes Agrum','€2.50',''],['Schweppes Tonic','€2.50',''],['Sanpellegrino','€2.50','']]},
{cat:'boissons',title:'Et de quoi se réchauffer ?',items:[['Espresso','€2.50',''],['Café normal','€2.50',''],['Cappuccino','€3.50',''],['Lait russe','€3.50',''],['Thé','€2.50','']]},
{cat:'vins',title:'À la vôtre !',items:[['1 verre vin blanc','€3.50',''],['1 verre vin rouge','€3.50',''],['1 verre rosé','€3.50',''],['1/4L vin blanc','€7.00',''],['1/4L vin rouge','€7.00',''],['1/4L rosé','€7.00',''],['1/2L vin blanc','€12.00',''],['1/2L vin rouge','€12.00',''],['1/2L rosé','€12.00',''],['Jupiler','€2.50',''],['Jupiler 0%','€2.50',''],['Maes','€2.50',''],['Super Bock','€3.50',''],['Kriek','€3.50',''],['Leffe Blonde','€3.50',''],['Leffe Brune','€4.50','']]},
{cat:'vins',title:'Apéritifs & digestifs',items:[['Martini blanc / rouge','€4.50',''],['Prosecco','€4.50',''],['Cynar','€4.50',''],['Porto blanc / rouge','€4.50',''],['Aperol Spritz','€7.00',''],['Campari','€7.00',''],['Corona','€4.50',''],['Amaro Averna','€4.50',''],['Amaretto Di Saronno','€4.50',''],['Limoncello','€4.50','']]}
];
const grid=document.querySelector('#menuGrid');function renderMenu(filter='all'){grid.innerHTML='';menuData.filter(s=>filter==='all'||s.cat===filter).forEach((s,i)=>{const art=document.createElement('article');art.className='menu-category reveal';art.innerHTML=`<h3>${s.title}</h3>`+s.items.map(it=>`<div class="menu-item"><b>${it[0]}</b><em>${it[1]}</em>${it[2]?`<p>${it[2]}</p>`:''}</div>`).join('');grid.appendChild(art);setTimeout(()=>art.classList.add('in'),60*i)})}renderMenu();document.querySelectorAll('.menu-controls button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.menu-controls button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMenu(b.dataset.filter)});
window.addEventListener('load',()=>setTimeout(()=>document.querySelector('#loader').classList.add('hide'),600));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const glow=document.querySelector('#cursorGlow');window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});
const header=document.querySelector('#header');window.addEventListener('scroll',()=>{header.style.transform=`translateX(-50%) scale(${scrollY>60?.985:1})`;const stage=document.querySelector('#pizzaStage img');if(stage){const r=document.querySelector('.showcase-3d').getBoundingClientRect();const p=Math.max(0,Math.min(1,-r.top/(r.height-innerHeight)));stage.style.transform=`rotateX(${58-p*36}deg) rotateZ(${-18+p*42}deg) scale(${1+p*.08})`;stage.style.filter=`saturate(${1+p*.25}) contrast(${1.05+p*.12})`}
const track=document.querySelector('#horizontalTrack');const sec=document.querySelector('.horizontal-section');if(track&&sec){const rect=sec.getBoundingClientRect();const max=track.scrollWidth-innerWidth+48;const prog=Math.max(0,Math.min(1,-rect.top/(rect.height-innerHeight)));track.style.transform=`translateX(${-max*prog}px)`}});
document.querySelectorAll('.feature-card,.menu-category').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;card.style.transform=`rotateY(${x*8}deg) rotateX(${-y*8}deg) translateY(-6px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
